name: Guardian
version: '${project.version}'
main: dev.trixxie.guardian.Guardian
api-version: 1.18
authors: [ Trixxie ]
description: Guardian makes the Minecraft pvp more fair
softdepend:
  - LibsDisguises
  - PlaceholderAPI
  - Factions
  - WorldGuard
commands:
  tag:
    usage: /<command>
    description: Check if you are combat tagged
  guardian:
    usage: /<command>
    description: Manage guardian
permissions:
  guardian.bypass:
    default: false
    description: Gives player immunity to combat tagging
